In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
mnist =pd.read_csv("train.csv")

In [4]:
mnist
#(rows,cols)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
mnist.head()
#label isalways y
#and we have 784 pixels

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
X= mnist.iloc[: ,1:].values #bcz we are accessing integer val 
# accesing number instead of categorical data
y=mnist["label"].values
#here we have used .numpy to convert it into numpy array

In [7]:
X.shape

(42000, 784)

In [8]:
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)
#this just for splitting train and test

In [ ]:

X_train.shape

In [ ]:
y_train.shape

In [ ]:
X_test.shape

In [ ]:
y_test.shape

In [ ]:
#we can apply kNN on this

In [ ]:
# def plot_image(img):
#     plt.imshow(img.reshape(28,28)) #this function gives u acolor map 
#     plt.show()

In [ ]:
def plot_image(img):
    plt.imshow(img.reshape(28,28) ,cmap="gray") #this function gives u acolor map 
    #imshow just plot img and in img u will get (1,784)
    
    #so converting 784 into 28x28  
    plt.show()
    #as the img is graay scale so if we dont put cmap it 
    #automatically put so some color imshow ()

In [ ]:
plot_image(X_train[60])
print(y_train[60])

# kNN

In [ ]:
def distance(pA, pB):
    return np.sum((pB - pA)**2)**0.5

In [ ]:
def kNN(X, y, x_query, k = 5):
    """
    X - > (m, 784)  np array (m is just number of eg. images)
    y - > (m,) np array
    x_query -> (1,874) np array
    k -> scaler  int
    
    do knn for classification
    """
    
    m = X.shape[0]
    distances = []
    for i in range(m):
        dis = distance(x_query, X[i])
        distances.append((dis, y[i]))
        
    distances = sorted(distances)
    distances = distances[:k]
    
    distances = np.array(distances)
    labels = distances[:, 1]
    
    
    uniq_label, counts = np.unique(labels, return_counts=True)

    pred = uniq_label[counts.argmax()]
    
    
    return int(pred)

In [ ]:
# prediciting label for test
kNN(X_train , y_train, X_test[235], k=7)
#X_test if for testing

In [ ]:
# displaying test image
plot_image(X_test[235])

In [ ]:
# actual label
y_test[235]
#this for checking that is X_train ==y_train

# Prediciting 100 Images

In [ ]:
predictions = []
for i in range(1000):
    p = kNN(X_train , y_train, X_test[i], k=7)
    predictions.append(p)

In [ ]:
predictions = np.array(predictions)

# Accuracy on 100 Images

In [ ]:
(y_test[:100] == predictions)

In [ ]:
(y_test[:100] == predictions).sum()/len(predictions) #or 100

# KNN From sklearn